 f_urllc_good:
  _target_: reput.peer.Peer
  behavior:
    0.0: { "latency": 4, "bandwith": 50, "loss": 70000 }
  transaction_duration: ${simulation.transaction_duration}
  total_capacity: ${simulation.capacity}
  breaking_rate: ${simulation.breaking_rate}
  peer_interactions: ${simulation.peer_interactions}
  initial_reput: ${simulation.initial_reput}
  transaction_type: ${transaction_selector:${simulation.fuzzy}}
  forgiveness_delay: ${simulation.forgiveness_delay}
  label: "urllc_good"
  dispersion: "low"
  usecase: "URLLC"
